### ISSUE TITLE
Comet tails dont work and KEX breaks rings

### ISSUE THREAD

**Issue by Galileo88** [StollD/KopernicusExpansion-Continued#2]
Gas giants and footprints work, which is good. Comet tails do not, which is bad ([LOGS](https://www.dropbox.com/s/kofhaep99pxb7qe/KEXcomettail.zip?dl=1)). The more pressing issue though is that it looks like KEX breaks rings :/

I noticed the issue with comet tails, procedural gas giants and footprints. Then i removed them all and tried with only footprints and got the same issue. I don't think its footprints causing the issue, but it may lie in the common.dll. Removing KEX restores the rings.

EDIT: I tried with just the Common.dll and the rings appear fine, but adding any other dll to it, footprints or comet tails, etc. breaks the rings again.

[Output log AND MM cache](https://www.dropbox.com/s/dc4qt3cscs3oiem/KEXtest2.zip?dl=1)

http://imgur.com/kPG7sO8
http://imgur.com/pMhO8gX

**Comment by StollD** [comment]
You don't need a Tails node anymore. Just put your comet tails directly into the CometTails node.

And regarding the rings: Try it again when 1.3.0-4 is released in a few minutes.

**Comment by Galileo88** [comment]
I'll be out of town for the next few days but I'll have someone else test it out. Thanks!

**Comment by Galileo88** [comment]
Also, if you want, I'll throw together a new examples bit for you when I get back if you haven't already
